---
swagger: "2.0"
info:
  description: "FRED is a tool for automatically producing RDF/OWL ontologies and\
    \ linked data from natural language sentences. The method is based on Combinatory\
    \ Categorial Grammar, Discourse Representation Theory, Linguistic Frames, and\
    \ Ontology Design Patterns. Results are enriched with NER and WSD.\n"
  version: "v1"
  title: "FRED API"
paths:
  /stlab-tools/fred:
    get:
      description: "Generate RDF from natural language text."
      operationId: "stlab_tools_fred_get"
      produces:
      - "application/rdf+xml"
      - "text/turtle"
      - "application/rdf+json"
      - "text/rdf+n3"
      - "text/rdf+nt"
      - "image/png"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "The authorization bearear. Type \"Bearer xxx-yyy-zzz\", where\
          \ is your secret token."
        required: true
        type: "string"
      - name: "text"
        in: "query"
        description: "The input natural language text."
        required: true
        type: "string"
      - name: "prefix"
        in: "query"
        description: "The prefix used for the namespace of terms introduced by FRED\
          \ in the output. If not specified fred: is used as default."
        required: false
        type: "string"
      - name: "namespace"
        in: "query"
        description: "The namespace used for the terms introduced by FRED in the output.\
          \ If not specified http://www.ontologydesignpatterns.org/ont/fred/domain.owl#\
          \ is used as default."
        required: false
        type: "string"
      - name: "wsd"
        in: "query"
        description: "Perform Word Sense Disambiguation on input terms. By default\
          \ it is set to false."
        required: false
        type: "boolean"
      - name: "wfd"
        in: "query"
        description: "Perform Word Frame Disambiguation on input terms in order to\
          \ provide alignments to WordNet synsets, WordNet Super-senses and Dolce\
          \ classes. By default it is set to false."
        required: false
        type: "boolean"
      - name: "wfd_profile"
        in: "query"
        description: "The profile associated with the Word Frame Disambiguation"
        required: false
        type: "string"
        default: "b"
        enum:
        - "b"
        - "d"
        - "t"
      - name: "tense"
        in: "query"
        description: "Include temporal relations between events according to their\
          \ grammatical tense. By default it is set to false."
        required: false
        type: "boolean"
      - name: "roles"
        in: "query"
        description: "Use FrameNet roles into the resulting ontology. By default it\
          \ is set to false."
        required: false
        type: "boolean"
      - name: "textannotation"
        in: "query"
        description: "The vocabulary used for annotating the text in RDF. Two possible\
          \ alternatives are available, i.e. EARMARK and NIF."
        required: false
        type: "string"
        default: "earmark"
        enum:
        - "earmark"
        - "nif"
      - name: "semantic_subgraph"
        in: "query"
        description: "Generate a RDF which only expresses the semantics of a sentence\
          \ without additional RDF triples, such as those containing text spans, part-of-speeches,\
          \ etc. By default it is set to false."
        required: false
        type: "boolean"
      responses:
        200:
          description: "The RDF produced by FRED for the text provided as input."
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions: {}
parameters:
  authorization:
    name: "Authorization"
    in: "header"
    description: "The authorization bearear. Type \"Bearer xxx-yyy-zzz\", where is\
      \ your secret token."
    required: true
    type: "string"
  text:
    name: "text"
    in: "query"
    description: "The input natural language text."
    required: true
    type: "string"
  prefix:
    name: "prefix"
    in: "query"
    description: "The prefix used for the namespace of terms introduced by FRED in\
      \ the output. If not specified fred: is used as default."
    required: false
    type: "string"
  namespace:
    name: "namespace"
    in: "query"
    description: "The namespace used for the terms introduced by FRED in the output.\
      \ If not specified http://www.ontologydesignpatterns.org/ont/fred/domain.owl#\
      \ is used as default."
    required: false
    type: "string"
  wsd:
    name: "wsd"
    in: "query"
    description: "Perform Word Sense Disambiguation on input terms. By default it\
      \ is set to false."
    required: false
    type: "boolean"
  wfd:
    name: "wfd"
    in: "query"
    description: "Perform Word Frame Disambiguation on input terms in order to provide\
      \ alignments to WordNet synsets, WordNet Super-senses and Dolce classes. By\
      \ default it is set to false."
    required: false
    type: "boolean"
  wfd_profile:
    name: "wfd_profile"
    in: "query"
    description: "The profile associated with the Word Frame Disambiguation"
    required: false
    type: "string"
    default: "b"
    enum:
    - "b"
    - "d"
    - "t"
  tense:
    name: "tense"
    in: "query"
    description: "Include temporal relations between events according to their grammatical\
      \ tense. By default it is set to false."
    required: false
    type: "boolean"
  roles:
    name: "roles"
    in: "query"
    description: "Use FrameNet roles into the resulting ontology. By default it is\
      \ set to false."
    required: false
    type: "boolean"
  textannotation:
    name: "textannotation"
    in: "query"
    description: "The vocabulary used for annotating the text in RDF. Two possible\
      \ alternatives are available, i.e. EARMARK and NIF."
    required: false
    type: "string"
    default: "earmark"
    enum:
    - "earmark"
    - "nif"
  semantic-subgraph:
    name: "semantic_subgraph"
    in: "query"
    description: "Generate a RDF which only expresses the semantics of a sentence\
      \ without additional RDF triples, such as those containing text spans, part-of-speeches,\
      \ etc. By default it is set to false."
    required: false
    type: "boolean"
